-- CreateTable
CREATE TABLE `Presensi` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `rombel` VARCHAR(191) NOT NULL,
    `idSiswa` VARCHAR(191) NOT NULL,
    `tipe` ENUM('IZIN', 'SAKIT', 'ALPHA', 'HADIR') NOT NULL DEFAULT 'HADIR',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Presensi` ADD CONSTRAINT `Presensi_rombel_fkey` FOREIGN KEY (`rombel`) REFERENCES `Kelas`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Presensi` ADD CONSTRAINT `Presensi_idSiswa_fkey` FOREIGN KEY (`idSiswa`) REFERENCES `PesertaDidik`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
